services:
  users-db:
    image: postgres:latest
    container_name: users-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - users-db-data:/var/lib/postgresql/data

  analytics-db:
    image: postgres:latest
    container_name: analytics-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics_db
    ports:
      - "5433:5432"
    volumes:
      - analytics-db-data:/var/lib/postgresql/data

volumes:
  users-db-data:
  analytics-db-data: