// <auto-generated />
using System;
using AnalyticsService.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnalyticsService.DataAccess.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250613115534_Change_InstrumentId_From_Guid_To_String")]
    partial class Change_InstrumentId_From_Guid_To_String
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnalyticsService.DataAccess.Entities.InstrumentDailyStat", b =>
                {
                    b.Property<string>("InstrumentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("InstrumentId", "Date");

                    b.ToTable("InstrumentDailyStats");
                });

            modelBuilder.Entity("AnalyticsService.DataAccess.Entities.InstrumentStat", b =>
                {
                    b.Property<string>("InstrumentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Bookmarks")
                        .HasColumnType("integer");

                    b.Property<int>("ContactViews")
                        .HasColumnType("integer");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("InstrumentId");

                    b.ToTable("InstrumentStats");
                });

            modelBuilder.Entity("AnalyticsService.DataAccess.Entities.UserStat", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("InstrumentsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLogins")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("UserStats");
                });
#pragma warning restore 612, 618
        }
    }
}
